on:
  repository_dispatch:
    types: [update_notes]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GH_PAT }}
      - run: |
          git submodule update --remote --merge
          git config --global user.name "James Home"
          git config --global user.email "jh@jameshome.com"
          git add .
          git commit -m "sync: notes" || exit 0
          git push
