name: Update Submodule
on:
  repository_dispatch:
    types: [notes_updated]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0
      - name: Git Pull and Commit
        run: |
          git submodule update --remote --merge
          git config --global url."https://x-access-token:${{ secrets.GH_PAT }}@github.com/".insteadOf "git@github.com:"
          git submodule update --remote --merge
          git config --global user.name "Obsidian on behalf of James Home"
          git config --global user.email "jh@jameshome.com"
          git add .
          git commit -m "chore: auto-sync vagabondage" || exit 0
          git push
